#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# Copyright (C) 2017, TQ Systems (ported mx28evk to em300)
# Christoph Krutz <christoph.krutz@tq-group.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

ifndef	CONFIG_SPL_BUILD
obj-y	:= em300.o
else
obj-y	:= iomux.o
endif
