#
# Copyright 2020 TQ Systems GmbH
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += em4xx.o

ifdef CONFIG_SPL_BUILD
obj-y += spl.o
obj-y += em4xx-512mb-lpddr4_timing.o
obj-y += em4xx-1gb-lpddr4_timing.o
obj-y += em4xx-2gb-lpddr4_timing.o
endif
